name: Spring Boot CI Deploy

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main
            - develop
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up JDK 21
              uses: actions/setup-java@v5
              with:
                    distribution: 'temurin'
                    java-version: '21'
                    cache: 'maven'

            - name: Install dependencies
              run: mvn clean install -DskipTests

            - name: Package application
              run: mvn -B clean package -DskipTests

            - name: Upload JAR artifact
              uses: actions/upload-artifact@v4
              with:
                    name: spring-boot-app
                    path: target/*.jar
    
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up JDK 21
              uses: actions/setup-java@v5
              with:
                    distribution: 'temurin'
                    java-version: '21'
                    cache: 'maven'

            - name: Run tests with coverage
              run: mvn -B clean test
        
            - name: Upload Test Coverage Report
              uses: actions/upload-artifact@v4
              with:
                    name: jacoco-coverage-report
                    path: target/site/jacoco/

    docker-build:
        runs-on: ubuntu-latest
        needs: 
            - build
            - test
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker Image
              run: docker build --platform linux/amd64 -t spring-boot-devops:latest .